# Generated by Django 5.2.7 on 2025-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ManyToManyField(null=True, to='store.promotion'),
        ),
    ]
