# Generated by Django 5.2.8 on 2025-11-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
