# Generated by Django 5.2.7 on 2025-11-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='store.promotion'),
        ),
    ]
