# Generated by Django 5.2.8 on 2025-11-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
        ),
    ]
